source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'LYNetworking' do
    pod 'LYNetworking', :path => '../'
    
    target 'LYNetworkingTests' do
        inherit! :search_paths
        
        
    end
end
